# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-08 14:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20151222_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, help_text='Des exemples d\'avatars sont disponibles sur <a href="https://www.avatarsdb.com">AvatarsDB</a>. Vous pouvez également utiliser <a href="https://www.gravatar.com">Gravatar</a> pour héberger et centraliser votre avatar. Vous pouvez également envoyer un avatar depuis votre disque en utilisant le champ ci-dessous.', validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name="Adresse de l'avatar, débutant par https://"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Visible uniquement par les utilisateurs connectés.', null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, help_text='Visible uniquement par les utilisateurs connectés.', max_length=100, verbose_name='Ville actuelle'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(blank=True, choices=[('style', 'Lexpage'), ('style_nowel', 'Nowel'), ('style_st_patrick', 'Saint-Patrick')], help_text='Laissez vide pour adopter automatiquement le thème du moment.', max_length=16, null=True, verbose_name='Thème'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True, help_text="L'adresse doit débuter par http:// ou https://", verbose_name='Adresse du site web'),
        ),
    ]
