# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aldp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(0, 'Saison'), (1, 'Manche')], verbose_name='Type de template')),
                ('name', models.CharField(max_length=80, verbose_name='Nom')),
                ('title', models.CharField(blank=True, help_text='Uniquement utilisé pour les messages démarrant une saison', max_length=80, null=True, verbose_name='Titre du message')),
                ('text', models.TextField(help_text='Mis en page avec le BBCode, plus une subsitition de quelques fieds.', verbose_name='Message')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='end_message_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aldp.MessageTemplate', verbose_name='Template utilisé pour la clôture'),
        ),
        migrations.AddField(
            model_name='season',
            name='start_message_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aldp.MessageTemplate', verbose_name="Template utilisé pour l'annonce"),
        ),
        migrations.AddField(
            model_name='turn',
            name='end_message_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aldp.MessageTemplate', verbose_name='Template utilisé pour la clôture'),
        ),
        migrations.AddField(
            model_name='turn',
            name='start_message_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aldp.MessageTemplate', verbose_name="Template utilisé pour l'annonce"),
        ),
    ]
