language: python
python:
- 3.4
install:
- pip install -r requirements.txt
- pip install -r requirements_tests.txt
script:
- python app/manage.py collectstatic --noinput
- coverage run --source app/ --omit */migrations/* --omit */management/* app/manage.py
  test
after_success:
- coveralls
addons:
  sauce_connect:
    username: AlexandreDecan
    access_key: iz5GMzmcSEa5gRIS7aSHN9dGVLsNoJ/dHNNC3x2rXQ7QAIO4LjZNBfT3pj6dbKVxWe1t8UKjqg9mJeUdbxgbhKM6f8QWDngLKfGZrQaRKErBCWE2EJgv1SlKcVuvpK/fkFglhF69kJyO+wwMrucFV8L75Ys+cUD1hm0s/05QCot3n/qB35QpJrZEJLWIC3XYRuZ44/e5YnylyKC0xVvct8tix5bmwLrL5LksZTtRccrlGzB9whSbdL0ijuGigjjQ4U2eeFB65FBKBS3HHLeVemPxakGiyMycTGTCH9IqSVVmyRD6HQN7R61TiHvJnuMT17F5Gz9O+0ubQiSwZZY322FxenGzpqsVj60EeoE8IiKm63xvstQQnSSg4I5nTdreNCBG/62XFI3GNlrLOfnI/3K8FwH8VLD80wkxjKOcEyUU6uPu2Z60gANipAfyAk/mv5tvTuYLjpDDKoHrKlXH5PHYhhOf++JzdXh+FygB4eaVaNUJkS+0VfqVPm0oJOtdaawB9v1yQ6HpRXFlep2fkbBzSartbseQbsIOJ0dlKEfXTEYmd7y6JcAyTXjVQRiqVUSF5Bv73u9r4+7T3paccn2pxiIwySistQHvlZMxktOzji6cS3pzkPqlm4csrl6ZkrQY+JtyR/S+qo+MqytIQlR/cx84tstFSRg+8zGtVpI=
