language: python
python:
- 3.4
install:
- pip install -r requirements.txt
- pip install -r requirements_tests.txt
script:
- python app/manage.py collectstatic --noinput
- coverage run --source app/ --omit */migrations/* --omit */management/* app/manage.py
  test
after_success:
- coveralls
addons:
  sauce_connect:
    username: Lexpage
    secure: NriMZc1hqp/Vu3IOsP95EykcGlUE+OGUDzmhDqPisSWLmvRScLt8bNVaZfBfoSsByCNDFHpT2nFCv0ZCK1FavNV18sLQKzVKRSytXPeYM9Fc0TwFtLIO3iHPj+zz7wrXo6rxw/7WqowK3dH43p68cbX3Rd4DPLAacy7G777aF/TI2VYqrd0IA91t98gq+L6Q0ycbte8DL1R4LD6yEBNbj92jAV+TEjTjtG/m/6dTXK+6nbfsqhlMzljdlD5UgY44L7Jxp+zKzPeIjk4y2JTPNFKopofbRQ7UgyYntGn0szANX/G3pAp7k90iQwr3Una5LXo8vb+Cqa63OSzlBFHp8VIIhUPcJcbX/e2+HrdaiEUSIQIaiVgSm6gnKAJi4udkNTzN1eozgG8m39cEJ57uVb2PiSdGddo8sB1SPPM9vGTiFb/y6vMHpurCEKl8oNRVVYD4/teHI3O+2NwdIHg47Ghxon2AGIobu1S6Xrl3ozvnMgbxYrDAx1uRLrHXktmSaIC9MMA1YLiPLgbuiDmNkU2lKTVjzO9FoOtoLxhDc1v6pAqCLhivQiV5kwSgU4ZugTUqgFArTe7xqvWmK28p8vfqEgLVVsZgbORzrdrd2PfmfHAxHFoWSSnrEL+gpnr9g107tvZHZWxmiti+DFIs6AAbtOF3HvhL/FhDJ0F1YBo=
