language: python
python:
- 3.4
sudo: true
dist: trusty
env:
  global:
  - DJANGO_SETTINGS_MODULE=settings_travis
  matrix:
  - SELENIUM_WEBDRIVER=selenium.webdriver.chrome.webdriver.WebDriver
  - SELENIUM_WEBDRIVER=selenium.webdriver.firefox.webdriver.WebDriver
before_install:
- wget https://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo mv chromedriver /usr/bin
install:
- pip install -r requirements_dev.txt
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
script:
- python app/manage.py collectstatic --noinput
- coverage run --source app/ --omit */migrations/* --omit */management/* app/manage.py test
after_script:
- python app/tests_helpers.py
after_success:
- coveralls
