language: python
python:
  - 3.4
install: 
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python app/manage.py collectstatic --noinput
  - coverage run --source app/ --omit */migrations/* app/manage.py test
after_success:
  - coveralls
