language: python
python:
- 3.4
install:
- pip install -r requirements_dev.txt
script:
- python app/manage.py collectstatic --noinput --settings=settings_dev
- coverage run --source app/ --omit */migrations/* --omit */management/* app/manage.py test --settings=settings_dev
after_success:
- coveralls
