# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slogan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Slogan',
            options={'ordering': ['date'], 'permissions': (('can_set_visible', 'Peut rendre visible'),)},
        ),
    ]
