# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('board', '0001_initial'), ('board', '0002_auto_20151222_1053'), ('board', '0003_auto_20170408_1400')]

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBoardLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Suivi',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Mis en page avec le BBCode.', verbose_name='Message')),
                ('moderated', models.BooleanField(default=False, help_text='Si le message est modéré, son auteur ne pourra plus le modifier.', verbose_name='Message modéré ?')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_post', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'ordering': ['date'],
                'get_latest_by': 'date',
                'permissions': (('can_moderate', 'Peut modérer'), ('can_destroy', 'Peut détruire')),
                'verbose_name': 'Message',
            },
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('text', models.TextField(verbose_name='Historique')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la modification')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='board.Message', verbose_name='Message')),
            ],
            options={
                'ordering': ['date'],
                'get_latest_by': 'date',
                'verbose_name': 'Édition de message',
                'verbose_name_plural': 'Éditions de message',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=90)),
                ('number', models.IntegerField(default=0, verbose_name='Nombre de messages')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_message', models.ForeignKey(db_constraint=False, default=-1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='board.Message', verbose_name='Dernier message')),
            ],
            options={
                'ordering': ['date_created'],
                'get_latest_by': 'date_created',
                'verbose_name': 'Discussion',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Thread', verbose_name='Sujet'),
        ),
        migrations.AddField(
            model_name='flag',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Message', verbose_name='Dernier message lu'),
        ),
        migrations.AddField(
            model_name='flag',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Thread', verbose_name='Sujet'),
        ),
        migrations.AddField(
            model_name='flag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together=set([('user', 'thread')]),
        ),
        migrations.AddField(
            model_name='blogboardlink',
            name='thread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='board.Thread'),
        ),
    ]
