# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-08 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20151222_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='last_message',
            field=models.ForeignKey(db_constraint=False, default=-1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='board.Message', verbose_name='Dernier message'),
        ),
    ]
