# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('notifications', '0001_initial'), ('notifications', '0002_auto_20160120_2343'), ('notifications', '0003_auto_20170408_1400')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('action', models.CharField(blank=True, default='', max_length=255, verbose_name='Action')),
                ('app', models.CharField(max_length=50, verbose_name='Application')),
                ('key', models.CharField(max_length=100, verbose_name='Clé')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'get_latest_by': 'date',
                'ordering': ['date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set([('app', 'key', 'recipient')]),
        ),
    ]
