# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 09:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('messaging', '0001_initial'), ('messaging', '0002_auto_20151222_1053')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('author', models.ForeignKey(on_delete=models.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': 'Message',
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='MessageBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_read', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), verbose_name='Dernière lecture')),
                ('is_starred', models.BooleanField(default=False, verbose_name='Favorites ?')),
                ('status', models.SmallIntegerField(choices=[(1, 'Normal'), (2, 'Archivée'), (-1, 'Supprimée')], default=1, verbose_name='État')),
            ],
            options={
                'ordering': ['-thread__last_message__date'],
                'verbose_name': 'Boîte de réception',
                'verbose_name_plural': 'Boîtes de réceptions',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Titre')),
                ('last_message', models.ForeignKey(db_constraint=False, default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='messaging.Message', verbose_name='Dernier message')),
            ],
            options={
                'ordering': ['-last_message__date'],
                'verbose_name': 'Conversation',
                'get_latest_by': 'last_message',
            },
        ),
        migrations.AddField(
            model_name='messagebox',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Thread', verbose_name='Conversation'),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Thread', verbose_name='Conversation'),
        ),
    ]
